branches:
  only:
  - master

language: python

python:
  - 3.4

install:
  - pip install -r requirements.txt --use-mirrors

script:
  - make html

notifications:
  email: false

before_install:
  - git submodule update --init --recursive

after_success: ./deploy.sh

sudo: false
