branches:
  only:
  - master

language: python
sudo: false

notifications:
  email: false

python:
  - 3.4

install:
  - git submodule update --init --recursive
  # Miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  - conda config --set always_yes yes
  # - conda update -q conda
  - conda info -a
  - conda env create
  - export PATH="$HOME/conda/envs/blog/bin:$PATH"

script:
  - make html

after_success: ./deploy.sh
