name: blog
channels:
  - anaconda-cluster
  - anaconda-adam
dependencies:
  - python=3
  - jupyter
  - nbconvert
  - pip:
    - pelican>=3.6.0
    - Markdown==2.6.2
    - jsonschema==2.4.0
    - mistune==0.5.1
    - pylint
